[package]
name = "shared_data"
version = "0.1.0"
edition = "2021"
authors = ["Anderson Martins <andmartinsjr@gmail.com>"]

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
crc32fast = "1.4.2"
