[package]
name = "collector"
version = "0.1.0"
edition = "2021"
authors = ["Anderson Martins <andmartinsjr@gmail.com>"]

[dependencies]
shared_data = { path = "../shared_data" }
sysinfo = { version = "0.30.12", features = ["apple-app-store"] }
thiserror = "1.0.61"
